sources:
  - name: raw
    schema: superstore_data_raw
    tables: 
      - name: branches 
        identifier: branches
        columns:
         - name: BRANCH_ID
           description: date for orders
           tests: 
             - not_null
         - name: REGION
           tests: 
             - not_null
         - name: CITY
           tests: 
             - not_null
         - name: TOWN
           tests:
             - not_null
         - name: BRANCH_TOWN
           tests:
             - not_null
         - name: LAT
           tests:
             - not_null
         - name: LON
           tests:
             - not_null
        tests: 
         - unique:
            column_name: 'BRANCH_ID || TOWN'
      - name : categories
        identifier: categories
        columns:
         - name: ITEMID
           tests: 
             - not_null
             - unique
         - name: CATEGORY1
           tests: 
             - not_null
         - name: CATEGORY1_ID
           tests: 
             - not_null
         - name: CATEGORY2
           tests: 
             - not_null
         - name: CATEGORY2_ID
           tests: 
             - not_null
         - name: CATEGORY3
           tests: 
             - not_null
         - name: CATEGORY3_ID
           tests: 
             - not_null
         - name: CATEGORY4
           tests: 
             - not_null
         - name: CATEGORY4_ID
           tests: 
             - not_null
         - name: BRAND
           tests: 
             - not_null
         - name: ITEMCODE
           tests: 
             - not_null
             - unique
         - name: ITEMNAME
           tests: 
             - not_null 
      - name : customers
        identifier: customers
        columns:
         - name: USERID
           tests: 
             - not_null
             - unique
         - name: USERNAME_
           tests: 
             - not_null
         - name: NAMESURNAME
           tests: 
             - not_null
         - name: STATUS_
           tests: 
             - not_null
         - name: USERGENDER
           tests: 
             - not_null
         - name: USERBIRTHDATE
           tests: 
             - not_null
         - name: REGION
           tests: 
             - not_null
         - name: CITY
           tests: 
             - not_null
         - name: TOWN
           tests: 
             - not_null
         - name: DISTRICT
           tests: 
             - not_null
         - name: ADDRESSTEXT
           tests: 
             - not_null
             - unique
                             
      - name : orders
        identifier: orders
        columns:
         - name: ORDERID
           tests: 
             - not_null
             - unique
         - name: BRANCH_ID
           tests: 
             - not_null
         - name: DATE_
           tests: 
             - not_null
         - name: USERID
           tests: 
             - not_null
         - name: NAMESURNAME
           tests: 
             - not_null
         - name: TOTALBASKET
           tests: 
             - not_null


